<?php

namespace App\Fields\Sections;

class OfferteAanvraag
{
    public static function get()
    {
        return [
            'key'        => 'layout_boozed_offerte_aanvraag',
            'name'       => 'offerte_aanvraag',
            'label'      => __('Offerte aanvraag', 'boozed'),
            'display'    => 'block',
            'sub_fields' => [
                [
                    'key'   => 'field_boozed_offerte_tab_step1',
                    'label' => __('Step 1: Start je aanvraag', 'boozed'),
                    'name'  => '',
                    'type'  => 'tab',
                ],
                [
                    'key'           => 'field_boozed_offerte_step1_label',
                    'label'         => __('Progress bar label', 'boozed'),
                    'name'          => 'offerte_step1_label',
                    'type'          => 'text',
                    'default_value' => 'Start je aanvraag',
                    'wrapper'       => ['width' => '50'],
                ],
                [
                    'key'           => 'field_boozed_offerte_intro_text',
                    'label'         => __('Intro text', 'boozed'),
                    'name'          => 'offerte_intro_text',
                    'type'          => 'wysiwyg',
                    'instructions'  => __('Introduction paragraph shown on step 1.', 'boozed'),
                    'wrapper'       => ['width' => '100'],
                ],
                [
                    'key'           => 'field_boozed_offerte_step1_title',
                    'label'         => __('Title', 'boozed'),
                    'name'          => 'offerte_step1_title',
                    'type'          => 'text',
                    'default_value' => 'Aanvraag starten',
                    'wrapper'       => ['width' => '50'],
                ],
                [
                    'key'           => 'field_boozed_offerte_step1_description',
                    'label'         => __('Description', 'boozed'),
                    'name'          => 'offerte_step1_description',
                    'type'          => 'textarea',
                    'rows'          => 3,
                    'wrapper'       => ['width' => '50'],
                ],
                [
                    'key'           => 'field_boozed_offerte_step1_cta_label',
                    'label'         => __('CTA button label', 'boozed'),
                    'name'          => 'offerte_step1_cta_label',
                    'type'          => 'text',
                    'default_value' => 'Begin jouw aanvraag >',
                    'wrapper'       => ['width' => '50'],
                ],
                [
                    'key'           => 'field_boozed_offerte_image_step1',
                    'label'         => __('Image', 'boozed'),
                    'name'          => 'offerte_image_step1',
                    'type'          => 'image',
                    'return_format' => 'id',
                    'preview_size'  => 'large',
                    'wrapper'       => ['width' => '50'],
                ],

                [
                    'key'   => 'field_boozed_offerte_tab_step2',
                    'label' => __('Step 2: Persoonlijke gegevens', 'boozed'),
                    'name'  => '',
                    'type'  => 'tab',
                ],
                [
                    'key'           => 'field_boozed_offerte_step2_label',
                    'label'         => __('Progress bar label', 'boozed'),
                    'name'          => 'offerte_step2_label',
                    'type'          => 'text',
                    'default_value' => 'Persoonlijke gegevens',
                    'wrapper'       => ['width' => '50'],
                ],
                [
                    'key'           => 'field_boozed_offerte_step2_title',
                    'label'         => __('Title', 'boozed'),
                    'name'          => 'offerte_step2_title',
                    'type'          => 'text',
                    'default_value' => 'Persoonlijke gegevens',
                    'wrapper'       => ['width' => '50'],
                ],
                [
                    'key'           => 'field_boozed_offerte_step2_subtitle',
                    'label'         => __('Subtitle / description', 'boozed'),
                    'name'          => 'offerte_step2_subtitle',
                    'type'          => 'textarea',
                    'rows'          => 2,
                    'default_value' => 'Vertel ons wat meer over jezelf.',
                    'wrapper'       => ['width' => '50'],
                ],
                [
                    'key'           => 'field_boozed_offerte_image_step2',
                    'label'         => __('Image', 'boozed'),
                    'name'          => 'offerte_image_step2',
                    'type'          => 'image',
                    'return_format' => 'id',
                    'preview_size'  => 'large',
                    'wrapper'       => ['width' => '50'],
                ],

                [
                    'key'   => 'field_boozed_offerte_tab_step3',
                    'label' => __('Step 3: Praktische informatie', 'boozed'),
                    'name'  => '',
                    'type'  => 'tab',
                ],
                [
                    'key'           => 'field_boozed_offerte_step3_label',
                    'label'         => __('Progress bar label', 'boozed'),
                    'name'          => 'offerte_step3_label',
                    'type'          => 'text',
                    'default_value' => 'Praktische informatie',
                    'wrapper'       => ['width' => '50'],
                ],
                [
                    'key'           => 'field_boozed_offerte_step3_title',
                    'label'         => __('Title', 'boozed'),
                    'name'          => 'offerte_step3_title',
                    'type'          => 'text',
                    'default_value' => 'Praktische informatie',
                    'wrapper'       => ['width' => '50'],
                ],
                [
                    'key'           => 'field_boozed_offerte_step3_subtitle',
                    'label'         => __('Subtitle / description', 'boozed'),
                    'name'          => 'offerte_step3_subtitle',
                    'type'          => 'textarea',
                    'rows'          => 2,
                    'default_value' => 'Vertel ons meer over je aanvraag.',
                    'wrapper'       => ['width' => '50'],
                ],
                [
                    'key'           => 'field_boozed_offerte_image_step3',
                    'label'         => __('Image', 'boozed'),
                    'name'          => 'offerte_image_step3',
                    'type'          => 'image',
                    'return_format' => 'id',
                    'preview_size'  => 'large',
                    'wrapper'       => ['width' => '50'],
                ],

                [
                    'key'   => 'field_boozed_offerte_tab_step4',
                    'label' => __('Step 4: Je experience', 'boozed'),
                    'name'  => '',
                    'type'  => 'tab',
                ],
                [
                    'key'           => 'field_boozed_offerte_step4_label',
                    'label'         => __('Progress bar label', 'boozed'),
                    'name'          => 'offerte_step4_label',
                    'type'          => 'text',
                    'default_value' => 'Je experience',
                    'wrapper'       => ['width' => '50'],
                ],
                [
                    'key'           => 'field_boozed_offerte_step4_title',
                    'label'         => __('Title', 'boozed'),
                    'name'          => 'offerte_step4_title',
                    'type'          => 'text',
                    'default_value' => 'Over je experience',
                    'wrapper'       => ['width' => '50'],
                ],
                [
                    'key'           => 'field_boozed_offerte_step4_subtitle',
                    'label'         => __('Subtitle / description', 'boozed'),
                    'name'          => 'offerte_step4_subtitle',
                    'type'          => 'textarea',
                    'rows'          => 3,
                    'default_value' => 'Om wat voor event/experience gaat het? Heb je een specifiek thema in gedachten of een lijstje met materialen die je nodig hebt? Vul dit dan hier in!',
                    'wrapper'       => ['width' => '50'],
                ],
                [
                    'key'           => 'field_boozed_offerte_image_step4',
                    'label'         => __('Image', 'boozed'),
                    'name'          => 'offerte_image_step4',
                    'type'          => 'image',
                    'return_format' => 'id',
                    'preview_size'  => 'large',
                    'wrapper'       => ['width' => '50'],
                ],

                [
                    'key'   => 'field_boozed_offerte_tab_general',
                    'label' => __('Algemeen', 'boozed'),
                    'name'  => '',
                    'type'  => 'tab',
                ],
                [
                    'key'           => 'field_boozed_offerte_help_text',
                    'label'         => __('Help / contact text', 'boozed'),
                    'name'          => 'offerte_help_text',
                    'type'          => 'textarea',
                    'rows'          => 2,
                    'default_value' => 'Heb je een andere vraag en ben je niet geholpen met dit formulier? Stuur dan gemakkelijk een mailtje naar info@boozed.nl',
                    'wrapper'       => ['width' => '100'],
                ],
                [
                    'key'           => 'field_boozed_offerte_recipient_email',
                    'label'         => __('Recipient email', 'boozed'),
                    'name'          => 'offerte_recipient_email',
                    'type'          => 'email',
                    'instructions'  => __('Where to send form submissions. Leave empty for site admin email.', 'boozed'),
                    'wrapper'       => ['width' => '100'],
                ],
            ],
        ];
    }
}
